server:
  port: 10001

spring:
  application:
    name: cloud-item-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    # 拆分数据源到独立database instance或者schema
    url: jdbc:mysql://127.0.0.1:3307/cloud-mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
  cloud:
    config:
      allow-override: true


# mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.hlkj.item.pojo

########################
###mybatis mapper配置
########################
#通用mapper配置

mapper:
  mappers: com.hlkj.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
#分页插件配置
pagehelper:
  support-methods-arguments: true
  helper-dialect: mysql
